{% set name = "spacy" %}
{% set version = "3.0.6" %}
{% set sha256sum = "5628ab89f1f568099c880b12a9c37f4ece29ab89260660cfdf728c02711879c5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  ignore_run_exports:
    - libgcc-ng
    - libstdcxx-ng
requirements:
  build:
    - {{ compiler('cxx') }}
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}
    - libstdcxx-ng  {{ libstdcxx }}
  host:
    - pip  {{ pip }}
    - python  {{ python }}
    - setuptools {{ setuptools }}     
    - numpy {{ numpy }} 
    - wheel {{ wheel }} 
    - cython {{ cython }}
    - cymem {{ cymem }} 
    - preshed {{ preshed }}
    - murmurhash {{ murmurhash }}
    - thinc {{ thinc }} 
    - cython-blis {{ cython_blis }}
    - pydantic {{ pydantic }}
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}
    - libstdcxx-ng  {{ libstdcxx }}
  run:
    - python {{ python }}
    - numpy {{ numpy }}
    - spacy-legacy {{ spacy_legacy }}
    - murmurhash {{ murmurhash }}
    - cymem {{ cymem }} 
    - preshed {{ preshed }} 
    - thinc {{ thinc }}
    - cython-blis {{ cython_blis }}
    - requests {{ requests }} 
    - wasabi {{ wasabi }} 
    - srsly {{ srsly }}
    - catalogue {{ catalogue }}
    - typer {{ typer }}
    - tqdm {{ tqdm }}
    - pathy {{ pathy }}
    - pydantic {{ pydantic }}
    - setuptools {{ setuptools }}
    - packaging >=20.0
    - typing_extensions {{ typing_extensions }}  # [py<38] 
    - jinja2
    # Use pins to control cos6/cos7 match
    - libgcc-ng {{ libgcc }}
    - libstdcxx-ng {{ libstdcxx }}

test:
  requires:
    - pytest
    - pytest-timeout
    - mock
    - importlib_metadata ==2.0.0
    - hypothesis
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}
    - libstdcxx-ng  {{ libstdcxx }}
  imports:
    - spacy
  commands:
    - python -m pytest --tb=native --pyargs {{ name }}

about:
  home: https://spacy.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Industrial-strength Natural Language Processing
  description: |
    spaCy is a library for advanced natural language processing in Python and
    Cython.
  doc_url: https://spacy.io
  dev_url: https://github.com/explosion/spaCy

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
